language: ruby

rvm:
  - 2.1

before_install:
  - openssl aes-256-cbc -K $encrypted_e04702d30b3c_key -iv $encrypted_e04702d30b3c_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config --global user.name "OnceMore2020"
  - git config --global user.email guanhwang2011@gmail.com
  - npm install gitbook-cli -g
  - npm install gitbook-ext -g
  - cd ~
  - git clone git@github.com:OnceMore2020/oncemore2020.github.io.git
  - gem install github-pages
  - cd oncemore2020.github.io
  - git branch
  - git checkout deploy

script:
  - jekyll build
  # a song of ice and fire
  - cd booksrc/asoiaf
  - gitbook-ext -i
  - gitbook-ext -p
  - gitbook install
  - gitbook build
  - cp _book/* ~/oncemore2020.github.io/books/asoiaf/ -rf
  # cpp primer
  - cd ~/oncemore2020.github.io/booksrc/cpp-primer
  - gitbook-ext -i
  - gitbook-ext -p
  - gitbook install
  - gitbook build
  - cp _book/* ~/oncemore2020.github.io/books/cpp-primer/ -rf
  # webdoc
  - cd ~/oncemore2020.github.io/lecturesrc
  - gitbook-ext -i
  - gitbook-ext -p
  - gitbook install
  - gitbook build
  - cp _book/* ~/oncemore2020.github.io/webdoc/ -rf

after_success:
  - cd ~/oncemore2020.github.io
  - git add assets
  - git add books
  - git add webdoc
  - git add blog
  - git add index.html
  - git commit -m ":black_nib:Updated$(date)"
  - git status
  - git checkout master
  - git merge deploy
  - git push -u origin HEAD:master --force

branches:
  except:
    - master

branches:
  only:
    - deploy
