language: ruby

rvm:
  - 2.1

before_install:
  - openssl aes-256-cbc -K $encrypted_e04702d30b3c_key -iv $encrypted_e04702d30b3c_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config --global user.name "OnceMore2020"
  - git config --global user.email guanhwang2011@gmail.com
  - cd ~
  - git clone git@github.com:OnceMore2020/oncemore2020.github.io.git blogbuild
  - cd blogbuild
  - git branch -a
  - git checkout -b deploy origin/deploy
  - gem install github-pages
  - npm install gitbook-cli -g
  - npm install gitbook-ext -g

script:
  - jekyll build
  - cp ~/blogbuild/blog ~/blog -rf
  # a song of ice and fire
  - cp ~/blogbuild/booksrc/asoiaf -r ~/asoiafsrc
  - cd ~/asoiafsrc
  - gitbook-ext -i
  - gitbook-ext -p
  - gitbook install
  - gitbook build
  # cpp primer
  - cp ~/blogbuild/booksrc/cpp-primer ~/cpp-primersrc
  - cd ~/cpp-primersrc
  - gitbook-ext -i
  - gitbook-ext -p
  - gitbook install
  - gitbook build
  # webdoc
  - cp ~/blogbuild/lecturesrc ~/lecturesrc
  - cd ~/lecturesrc
  - gitbook-ext -i
  - gitbook-ext -p
  - gitbook install
  - gitbook build
  # cp build files
  - cd ~/buildblog
  - git checkout master
  - cp ~/blog ~/blogbuild/blog -rf
  - cp ~/asoiafsrc/_book/* ~/blogbuild/books/asoiaf/ -rf
  - cp ~/cpp-primersrc/_book/* ~/blogbuild/books/cpp-primer/ -rf
  - cp ~/lecturesrc/_book/* ~/blogbuild/webdoc/ -rf

after_success:
  - git add --all
  - git commit -m ":black_nib:Updated$(date)"
  - git status
  - git push -u origin HEAD:master --force

branches:
  except:
    - master

branches:
  only:
    - deploy
