title: OnceMore2020
url:              http://oncemore2020.github.io
#url:              http://192.168.1.153:4000

owner:
  name:           王思墨
  weibo:          2615146412

gems:
  - jekyll-sitemap
  - jekyll-paginate

timezone:    Asia/Shanghai
permalink:   /:categories/:title/
future:     true
lsi: false
safe: true
incremental: false
highlighter: rouge
excerpt_separator: ""

paginate: 6
paginate_path: "/blog/page:num"

exclude: ['booksrc', 'lecturesrc']

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
