title: OnceMore2020
#url:              http://oncemore2020.github.io
url:              http://192.168.1.153:4000

owner:
  name:           王思墨
  weibo:          2615146412

gems:
  - jekyll-sitemap
  - jekyll-paginate

timezone:    Asia/Shanghai
permalink:   /:categories/:title/
incremental: false
excerpt_separator: ""

paginate: 5
paginate_path: "/blog/page:num"

exclude: ['booksrc', 'lecturesrc']
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
