title: OnceMore2020
reading_time:     true
words_per_minute: 60
url:              https://oncemore2020.github.io
enforce_ssl: oncemore2020.github.io

# Owner/author information
owner:
  name:           王思墨
  email:          guanhwang2011@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  weibo:          2615146412
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:   https://plus.google.com/110411659539252839234

gems:
  - jekyll-sitemap
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5
paginate_path: "/blog/page:num"

excerpt_separator: ""

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
